### PR TITLE
1.18.x

### PR DESCRIPTION
**Pull request by supersaiyansubtlety**
Just updated dependencies in gradpel.properties and fabric.mod.json for 1.18(.1).

### CODE REVIEW

**Comment by JacktheDevel0per** [comment]
ok I am Going To add this but Before I am Going to Look it over.

**Comment by JacktheDevel0per** [comment]
Merged Gonna Test then fix anything that may break, Most likely Nothing

**Comment by JacktheDevel0per** [comment]
does it work / Are you satisfied with it. also I am Going to do a 3 Version not Rewrite but make them the same with tweaks with some code changes in the 1.17-1.18 update

**Comment by supersaiyansubtlety** [comment]
> does it work / Are you satisfied with it. also I am Going to do a 3 Version not Rewrite but make them the same with tweaks with some code changes in the 1.17-1.18 update

I'm confused, is there a question here?

**Comment by JacktheDevel0per** [comment]
**Are you satisfied with it**? Weird question now that I think about it but this was the question

**Comment by supersaiyansubtlety** [comment]
Yeah looks fine to me.

**Pull request merged**
